### ISSUE TITLE
Allow log scrolling

### ISSUE THREAD

**Issue by brooksmtownsend** [gin66/tui-logger#12]
Currently, if logs scroll out of the frame, there is no way (other than changing log levels) to view logs that have scrolled out of the frame. This can be problematic in just-noisy-enough applications where there are enough logs to overflow out of the window, as there's no way to view if they were successful or not.

It would be awesome if there was a way to scroll the output log (potentially by focusing on the log widget, and using a KeyModifier + UP/DOWN). I see in your implementation that you use the `offset` field of `TuiWidgetInnerState` to control how far the window has scrolled, but since that field is private I was unable to make any manual modifications.

I'm using the logger widget pretty extensively [in the wash project on GitHub](https://github.com/wasmCloud/wash/), and would be happy to contribute a PR if we wanted to talk about a solution here... I implemented scrolling in an output window by using the SHIFT+UP/DOWN key combination to increase/decrease the scroll offset. [Code for scrolling up](https://github.com/wasmCloud/wash/blob/main/src/up.rs#L267-L271).

It would also be neat to be able to set the title log / title target attributes of the `TuiLoggerSmartWidget`. I don't intend on replacing them, but simply buffering them with a space character on each side increases readability with the widget borders in my opinion. You can see below the `r` seems almost connects with the border.
![image](https://user-images.githubusercontent.com/12040685/108268612-c7428780-713a-11eb-903f-610eb37803b9.png)

Also, please let me know if I'm missing an obvious way to scroll or do this as the crate exists today (I'm using version `0.4.13` with the "tui-crossterm" feature).

Thanks for the awesome project.

**Comment by gin66** [comment]
Thanks for the detailed proposal and use of tui-logger in your nifty wash application. 

The feature to have scroll back, I have wished already for a long time, but I saw only problems. After revisiting now with a fresh look , I have come up with a quite simple approach and it works quite well. The title change was too quite straightforward, so I hope the v0.6.0 will fulfill all your needs.

Just it will be some work for you, because I have removed the dependency on termion and crossterm completely by defining events to be applied to the TuiWidgetState. Consequently, no dispatcher anymore and the translation of termion, crossterm, ...(whatever tui_rs supports) into events has to be done by the application (see demo.es for a quick-n-dirty implementation).

From my point of view, this is a much better approach than trying to keep up with tui_rs for supporting so many different terminal apis.

**Comment by gin66** [comment]
The naming of the events are straightforward from past key bindings, but in some respect bit dumb. So room for improvements in future releases.

**Comment by brooksmtownsend** [comment]
Thanks for the quick response! Looking forward to `v0.6.0` then 🙂 . I'm fine with removing the dispatcher and referencing the demo to get rid of the explicit crossterm dependency, once `v0.6.0` is released I'll give it a shot. Let me know if I can be of use while you're working on this

**Comment by gin66** [comment]
is released. on crates and github.

**Comment by brooksmtownsend** [comment]
I may be misunderstanding then, is log scrolling implemented in `v0.6.0`? If so, I'll give it a shot, but I was under the impression that it was still in proress.

**Comment by gin66** [comment]
is implemented

**Comment by brooksmtownsend** [comment]
Great! I'll give the upgrade a try then

**Comment by gin66** [comment]
Only wondering::
> With the upgrade of tui_logger to 0.6.0, we had to modify our terminal backend from crossterm to termion, which accounts for most of the code in this PR.

tui_logger is now terminal backend agnostic. So wonder, how comes this conclusion ?

**Comment by brooksmtownsend** [comment]
@gin66 I largely followed the `demo` code, I can see now how the logger is backend agnostic... I did like how crossterm was setup so I may re-introduce that as my backend depending on how termion can be. I misunderstood that removing the "crossterm" feature was because you are backend agnostic, rather than enforcing termion only
