### ISSUE TITLE
Slog support

### ISSUE THREAD

**Issue by lovesegfault** [gin66/tui-logger#6]
It'd be nice if slogger was supported alongside `log`

**Comment by gin66** [comment]
I have had a look at slogger, and feel it is bit complex (aka not KISS). From my understanding, it is not a replacement for log, because library modules will still use log. With several library modules hardcoded to use log, and own modules using slogger, then there are too different logger systems. From the documentation I could not find the hint, that log could be completely replaced for included modules by slog....

If my understanding is not correct, then please help to clarify.

**Comment by icy-ux** [comment]
Slog looks complicated but the core idea is actually pretty simple.

It would be really helpful for us if `tui-logger` supported `slog`, because `tui-logger` is a fantastic way to show logs to the user while also showing other program output at the same time (in a different `tui` widget). At the same time, `slog` is a fantastically powerful and flexible way to route and handle log data, which makes it very easy to log to multiple backends with different log levels and the like.

For `tui-logger` to support `slog` it *only* nees to implement [slog::Drain](https://docs.rs/slog/2.5.2/slog/trait.Drain.html) ... that would let `tui-logger` be smoothly and easily integrated into a larger `slog` logging infrastructue. If `tui-logger` implements `slog::Drain` then that just means it can take slog logging messages, and implementing Drain only requires one method and two associated types :)
